Update init to exit on error with patches for failing scripts (#29)
Override `rpi-resizerootfs` to resolve e2fsck failure

diff --git a/initramfs_build/overlay/init b/initramfs_build/overlay/init
--- a/initramfs_build/overlay/init
+++ b/initramfs_build/overlay/init
@@ -1,5 +1,8 @@
 #!/bin/sh
 
+# Exit on any failure
+set -e
+
 # Default PATH differs between shells, and is not automatically exported
 # by klibc dash.  Make it consistent.
 export PATH=/sbin:/usr/sbin:/bin:/usr/bin
@@ -223,16 +226,19 @@ fi
 mount -t tmpfs -o "nodev,noexec,nosuid,size=${RUNSIZE:-10%},mode=0755" tmpfs /run
 mkdir -m 0700 /run/initramfs
 
-if [ -n "$log_output" ]; then
-	exec >$log_output 2>&1
-	unset log_output
-fi
+# TODO: This fails at `exec`
+#if [ -n "$log_output" ]; then
+#  [ -f "${log_output}" ] || touch "${log_output}"
+#  echo "redirecting output to ${log_output}"
+#	exec >$log_output 2>&1
+#	unset log_output
+#fi
 
 maybe_break top
 
 # Don't do log messages here to avoid confusing graphical boots
-run_scripts /scripts/init-top
-
+run_scripts /scripts/init-top || echo "init-top failed"  # TODO: why does `udev` fail here?
+sleep 1  # TODO: What is this fixing?
 maybe_break modules
 [ "$quiet" != "y" ] && log_begin_msg "Loading essential drivers"
 [ -n "${netconsole}" ] && /sbin/modprobe netconsole netconsole="${netconsole}"
@@ -262,7 +268,7 @@ log_begin_msg "Mounting root file system"
 parse_numeric "${ROOT}"
 maybe_break mountroot
 mount_top
-mount_premount
+mount_premount || echo "mount_premount failed"  # TODO: Why?
 mountroot
 log_end_msg
 
@@ -273,7 +279,7 @@ if read_fstab_entry /usr; then
 fi
 
 # Mount cleanup
-mount_bottom
+mount_bottom || echo "mount_bottom failed"  # TODO: Why?
 nfs_bottom
 local_bottom
 
@@ -330,7 +336,7 @@ if [ -n "${ROOT_ROPATH}" ]; then
   [ "$quiet" != "y" ] && log_begin_msg "Running /scripts/init-bottom"
   # We expect udev's init-bottom script to move /dev to ${rootmnt}/dev
   [ -d "${rootmnt}/dev" ] || mkdir "${rootmnt}/dev"  # Ensure new directory exists
-  run_scripts /scripts/init-bottom
+  run_scripts /scripts/init-bottom || echo "init-bottom failed"  # TODO: why?
   [ "$quiet" != "y" ] && log_end_msg
   # Move /run to the root
   mount -n -o move /run ${rootmnt}/run
